allowBuilds:
  '@firebase/util': set this to true or false
  '@google/genai': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
